steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://speech2123123/Speech2t.json', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/healthbuddy:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/healthbuddy:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'healthbuddy',
    '--image', 'gcr.io/$PROJECT_ID/healthbuddy:$COMMIT_SHA',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'GOOGLE_APPLICATION_CREDENTIALS=/app/Speech2t.json,OPENAI_API_KEY=$$(gcloud secrets versions access latest --secret="openai-api-key")'
  ]

substitutions:
  _PORT: "8080"

images:
- 'gcr.io/$PROJECT_ID/healthbuddy:$COMMIT_SHA'
